spring:
  application:
    name: ticket

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true

server:
  port: 19094


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
