spring:
  application:
    name: user
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:18080
  
---
spring:
  application:
    name: user
  profiles:
    active: prod
  config:
    import: optional:configserver:http://3.37.29.71/:18080