spring:
  application:
    name: ticket

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
