spring:
  application:
    name: queue
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:18080

---
spring:
  application:
    name: queue
  profiles:
    active: prod
  config:
    import: optional:configserver:http://3.37.29.71:18080