spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

springdoc:
  swagger-ui:
    urls[0]:
      name: 인증 명세서
      url: /swagger/auth/v3/api-docs
    urls[1]:
      name: 공연 명세서
      url: /swagger/performances/v3/api-docs
    urls[2]:
      name: 티켓 명세서
      url: /swagger/tickets/v3/api-docs
    urls[3]:
      name: 주문 명세서
      url: /swagger/orders/v3/api-docs
    urls[4]:
      name: 결제 명세서
      url: /swagger/payments/v3/api-docs
    urls[5]:
      name: 유저 명세서
      url: /swagger/users/v3/api-docs
    use-root-path: true