spring:
  application:
    name: gateway
  profiles:
    active: local
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:18080

---
spring:
  application:
    name: gateway
  profiles:
    active: prod
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:ec2-3-37-29-71.ap-northeast-2.compute.amazonaws.com:18080