spring:
  application:
    name: eureka


server:
  port: 19090

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://13.125.41.207:19090/eureka
  instance:
    hostname: 13.125.41.207

logging:
  level:
    feign: DEBUG