spring:
  application:
    name: payment
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:18080

---
spring:
  application:
    name: payment
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config:18080