spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 validate, create, create-drop 중에서 선택
    show-sql: true # SQL 로그 출력 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect