global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "eureka"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:19090"]
  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19091" ]
  - job_name: "order"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19095" ]
  - job_name: "payment"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19096" ]
  - job_name: "performance"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19093" ]
  - job_name: "ticket"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19094" ]
  - job_name: "user"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:19097" ]