spring:
  application:
    name: performance

  datasource:
    url: jdbc:postgresql://13.125.41.207:5432/performance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true

  data:
    elasticsearch:
      rest:
        uris: http://13.125.41.207:9200
        username: elastic
        password: 8zUSBpEzJmYnTn=EUZuR

server:
  port: 19093

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://13.125.41.207:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

