spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/performance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    elasticsearch:
      rest:
        uris: localhost:9200
        username: elastic
        password: 8zUSBpEzJmYnTn=EUZuR

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

