spring:
  application:
    name: performance
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:18080

---
spring:
  application:
    name: performance
  profiles:
    active: prod
  config:
    import: optional:configserver:ec2-3-37-29-71.ap-northeast-2.compute.amazonaws.com:18080