spring:

  datasource:
    url: jdbc:postgresql://${HOST_URI}/performance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true

  data:
    elasticsearch:
      rest:
        uris: ${HOST_URI}:9200
        username: elastic
        password: ${ELASTIC_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${HOST_URI}:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

