name: Spring boot CI/CD with AWS EC2, ECR

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: pwd

      - run: ls -al

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test --warning-mode=all

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

            # Docker 이미지 빌드
      - name: Build Docker images
        run: |
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-user:latest \
              --build-arg FILE_DIRECTORY=user -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-payment:latest \
              --build-arg FILE_DIRECTORY=payment -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-order:latest \
              --build-arg FILE_DIRECTORY=order -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-ticket:latest \
              --build-arg FILE_DIRECTORY=ticket -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-performance:latest \
              --build-arg FILE_DIRECTORY=service/coupon/coupon-api -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-eureka:latest \
              --build-arg FILE_DIRECTORY=eureka -f ./Dockerfile .
            docker build -t ${{ env.DOCKER_USERNAME }}/codeterian-gateway:latest \
              --build-arg FILE_DIRECTORY=gateway -f ./Dockerfile .

      # Docker Hub에 이미지 푸시
      - name: Push Docker image to Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-user:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-payment:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-order:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-ticket:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-performance:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-eureka:latest
          docker push ${{ env.DOCKER_USERNAME }}/codeterian-gateway:latest
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose -f ./docker-compose-deploy.yml down
            docker rm -f codeterian-user
            docker rm -f codeterian-ticket
            docker rm -f codeterian-order
            docker rm -f codeterian-payment
            docker rm -f codeterian-performance
            docker rm -f codeterian-eureka
            docker rm -f codeterian-gateway
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-user:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-ticket:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-order:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-performance:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-payment:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-eureka:latest
            docker pull ${{ env.DOCKER_USERNAME }}/codeterian-gateway:latest
            docker compose -f ./docker-compose-deploy.yml up -d